### PR TITLE
fix idle cam kvp

### LINKED ISSUE #86: Idle cam will be (re)enabled by rpemotes-reborn if key was not set
**Describe the bug**
Current implementation of NoIdleCam will cause DisableIdleCamera(false) to be called if key idleCam is nil (i.e. if the user never entered /idlecamon or /idlecamoff before), overriding the existing state of the idle camera without explicit user input

**To Reproduce**
Steps to reproduce the behaviour:
1. Disable idle cam using DisableIdleCamera before rpemotes-reborn starts
2. Start rpemotes-reborn
3. Observe that the idle camera is reenabled

**Expected behaviour**
Idle camera state should not be touched unless explicitly changed via entering the /idlecamon or /idlecamoff

**Additional context**
Discovered when disabling idle camera in qbx-core didn't appear to work for some reason

### PR DESCRIPTION
**Pull request by Mathu-lmn**
fixes #86

### CODE REVIEW

File: client/NoIdleCam.lua [hunk 1]
```diff
@@ -17,13 +17,18 @@ RegisterCommand('idlecamon', function() -- help2 31, 167, 9
...
 
 CreateThread(function()
     TriggerEvent("chat:addSuggestion", "/idlecamon", "Re-enables the idle cam")
     TriggerEvent("chat:addSuggestion", "/idlecamoff", "Disables the idle cam")
 
-    local idleCamDisabled = GetResourceKvpString("idleCam") == "off"
+    local idleCamKvp = GetResourceKvpInt("idleCam")
+    if idleCamKvp ~= 0 and idleCamKvp ~= 1 then
+        return
+    end
```
Comment (TheIndra55) [inline client/NoIdleCam.lua:30]: Isn't this operation always no-op since it will always return either 0 (default) or 1?

Comment (Mathu-lmn) [reply client/NoIdleCam.lua:30]: The idea was that if the convar is not set, it won't call the native (related to https://github.com/alberttheprince/rpemotes-reborn/issues/86) but I haven't actually tested it hence the PR

Comment (TheIndra55) [reply client/NoIdleCam.lua:30]: Correct, but when the convar is not set it will return 0.

Comment (Mathu-lmn) [reply client/NoIdleCam.lua]: Should be better with my last commit

**Review by TheIndra55 — APPROVED** [review]
